### ISSUE TITLE
패키지 구조 및 객체의 형태 구체화 

### ISSUE THREAD

**Issue by dennis0324** [dennis0324/jebi#2]
위에서 언급했던 파일 구조체, 객체 구체화 뿐만 아니라 사용 단어에 대해서 서로 맞춰서 해야 될 것 같다는 생각이 듭니당.
- [x] 프로젝트 구조 정하기
- [x] 클래스 메소드 이름

**Comment by jdeokkim** [comment]
매우 나이스!!
